name: publish

on:
  push:
    tags:
      - 'v*'

env:
  BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
  BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}

jobs:
  publish-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: CALL gradlew.bat linkReleaseSharedMingwX64
        shell: cmd
      - uses: actions/upload-artifact@v2
        with:
          name: decsync.dll
          path: build/bin/mingwX64/releaseShared/decsync.dll
      - run: CALL gradlew.bat publishMingwX64PublicationToMavenRepository
        shell: cmd
  publish-linux-and-misc:
    needs: [publish-windows]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./gradlew linkReleaseSharedLinuxX64
      - uses: actions/upload-artifact@v2
        with:
          name: libdecsync.so
          path: build/bin/linuxX64/releaseShared/libdecsync.so
      - run: ./gradlew publish
      - run: ./create-deb.sh
      - uses: actions/upload-artifact@v2
        with:
          name: libdecsync.deb
          path: deb.deb
